export const categories = [
    "Web, Mobile & Software Dev",
    "Design & Creative",
    "Admin Support",
    "IT & Networking",
    "Writing",
    "Data Science & Analytics",
    "Sales & Marketing",
    "Translation",
    "Engineering & Architecture",
    "Legal"
];

export const WebOption = [
    "All Web, Mobile & Software Dev",
    "Desktop Software Development",
    "Ecommerce Development",
    "Game Development",
    "Mobile Development",
    "Product Management",
    "Scripts & Utilities",
    "Web Development",
    "Web & Mobile Design",
    "Other - Software Development"
];
export const DesignOption = [
    "All Design & Creative",
    "Animation",
    "Audio Production",
    "Graphic Design",
    "Illustration",
    "Logo Design & Branding",
    "Photography",
    "Presentations",
    "Video Production",
    "Other - Design & Creative"
];
export const AdminOption = [
    "All Admin Support",
    "Data Entry",
    "Personal / Virtual Assistant",
    "Project Management",
    "Transcription",
    "Web Research",
    "Other - Admin Support"
];
export const ITOption = [
    "All IT & Networking",
    "Database Administration",
    "ERP / CRM Software",
    "Information Security",
    "Network & System Administration",
    "Other - IT & Networking"
];
export const WritingOption = [
    "All Writing",
    "Academic Writing & Research",
    "Article & Blog Writing",
    "Copywriting",
    "Creative Writing",
    "Editing & Proofreading",
    "Resumes & Cover Letters",
    "Technical Writing",
    "Web Content",
    "Other - Writing"
];
export const SalesOption = [
    "All Sales & Marketing",
    "Display Advertising",
    "Email & Marketing Automation",
    "Lead Generation",
    "Market & Customer Research",
    "Marketing Strategy",
    "Other - Sales & Marketing"
];
export const AnalyticsOption = [
    "All Data Science & Analytics",
    "A/B Testing",
    "Data Visualization",
    "Data Extraction / ETL",
    "Data Mining & Management",
    "Machine Learning",
    "Quantitative Analysis",
    "Other - Data Science & Analytics"
];
export const EngineeringOption = [
    "All Engineering & Architecture",
    "3D Modeling & CAD",
    "Architecture",
    "Chemical Engineering",
    "Civil & Structural Engineering",
    "Contract Manufacturing",
    "Electrical Engineering",
    "Interior Design",
    "Mechanical Engineering",
    "Other - Engineering & Architecture"
];
export const LegalOption = [
    "All Legal",
    "Contract Law",
    "Corporate Law",
    "Criminal Law",
    "Family Law",
    "Intellectual Property Law",
    "Paralegal Services",
    "Other - Legal"
];
export const TranslationOption = [
    "All Translation",
    "General Translation",
    "Legal Translation",
    "Medical Translation",
    "Technical Translation"
];
export const certeficateOption = [
    "English",
    "Frensh",
    "Arabic",
    "Design",
    "Animation",
    "Audio Production",
    "Graphic Design",
    "Illustration",
    "Logo Design & Branding",
    "Photography",
    "Photoshop",
    "3D Modeling & CAD",
    "unity",
    "Java",
    "Javascript",
    "Html5",
    "CSS",
    "ReactJS",
    "React native",
    "Angular",
    "Vue",
    "Architecture",
    "Typography",
    "Interior Design",
    "Mechanical Engineering"
];

export const countries = [
    "Afghanistan",
    "Aland Islands",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua And Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia",
    "Bosnia And Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Cayman Islands",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands",
    "Colombia",
    "Comoros",
    "Congo",
    "Congo, Democratic Republic",
    "Cook Islands",
    "Costa Rica",
    "Cote D'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Falkland Islands (Malvinas)",
    "Faroe Islands",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island & Mcdonald Islands",
    "Holy See (Vatican City State)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Republic Of",
    "Iraq",
    "Ireland",
    "Isle Of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libyan Arab Jamahiriya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia, Federated States Of",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "Netherlands Antilles",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestinian Territory, Occupied",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Reunion",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Saint Barthelemy",
    "Saint Helena",
    "Saint Kitts And Nevis",
    "Saint Lucia",
    "Saint Martin",
    "Saint Pierre And Miquelon",
    "Saint Vincent And Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome And Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia And Sandwich Isl.",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svalbard And Jan Mayen",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad And Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks And Caicos Islands",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "United States Outlying Islands",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Viet Nam",
    "Virgin Islands, British",
    "Virgin Islands, U.S.",
    "Wallis And Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];
