export const categories = [
  { label: "Web, Mobile & Software Dev", value: "Web" },
  { label: "Design & Creative", value: "Design " },
  { label: "Admin Support", value: "Admin" },
  { label: "IT & Networking", value: "IT" },
  { label: "Writing", value: "Writing" },
  { label: "Data Science & Analytics", value: "Data" },
  { label: "Sales & Marketing", value: "Sales" },
  { label: "Translation", value: "Translation" },
  { label: "Engineering & Architecture", value: "Engineering" },
  { label: "Legal", value: "Legal" }
];

export const skills = [
  { label: "Wireframes", value: "Wireframes" },
  { label: "UI design", value: "UI design" },
  { label: "Software architecting", value: "Software architecting" },
  { label: "Front-end coding", value: "Front-end coding" },
  { label: "Back-end integration & APIs", value: "Back-end integration & APIs" }
];
export const experience = [
  { label: "one year", value: "1" },
  { label: "two years", value: "2" },
  { label: "three years", value: "3" },
  { label: "plus five years", value: "5" }
];
export const WebOption = [
  { label: "All Web, Mobile & Software Dev", value: "Allweb" },
  { label: "Desktop Software Development", value: "Desktop" },
  { label: "Ecommerce Development", value: "Ecommerce" },
  { label: "Game Development", value: "Game" },
  { label: "Mobile Development", value: "Mobile" },
  { label: "Product Management", value: "Product" },
  { label: "Scripts & Utilities", value: "Scripts" },
  { label: "Web Development", value: "Web" },
  { label: "Web & Mobile Design", value: "Web & Mobile Design" },
  { label: "Other - Software Development", value: "Other" }
];
export const DesignOption = [
  { label: "All Design & Creative", value: "AllDesign" },
  { label: "Animation", value: "Animation" },
  { label: "Audio Production", value: "Audio" },
  { label: "Graphic Design", value: "Graphic" },
  { label: "Illustration", value: "Illustration" },
  { label: "Logo Design & Branding", value: "Logo" },
  { label: "Photography", value: "Photography" },
  { label: "Presentations", value: "Presentations" },
  { label: "Video Production", value: "Video" },
  { label: "Other - Design & Creative", value: "Other" }
];
export const AdminOption = [
  { label: "All Admin Support", value: "All" },
  { label: "Data Entry", value: "Data Entry" },
  { label: "Personal / Virtual Assistant", value: "Personal" },
  { label: "Project Management", value: "Project" },
  { label: "Transcription", value: "Transcription" },
  { label: "Web Research", value: "Web Research" },
  { label: "Other - Admin Support", value: "Other - Admin" }
];
export const ITOption = [
  { label: "All IT & Networking", value: "All" },
  { label: "Database Administration", value: "Database" },
  { label: "ERP / CRM Software", value: "Software" },
  { label: "Information Security", value: "Information" },
  { label: "Network & System Administration", value: "Network" },
  { label: "Other - IT & Networking", value: "Other" }
];

export const WritingOption = [
  { label: "All Writing", value: "All Writing" },
  { label: "Academic Writing & Research", value: "Academic" },
  { label: "Article & Blog Writing", value: "Article" },
  { label: "Copywriting", value: "Copywriting" },
  { label: "Creative Writing", value: "Creative" },
  { label: "Editing & Proofreading", value: "Editing" },
  { label: "Resumes & Cover Letters", value: "Resumes" },
  { label: "Technical Writing", value: "Technical" },
  { label: "Web Content", value: "Web" },
  { label: "Other - Writing", value: "Other" }
];

export const SalesOption = [
  {
    label: "All Sales & Marketing",
    value: "All Sales & Marketing"
  },
  { label: "Display Advertising", value: "Display Advertising" },
  {
    label: "Email & Marketing Automation",
    value: "Email & Marketing Automation"
  },
  { label: "Lead Generation", value: "Lead Generation" },
  {
    label: "Market & Customer Research",
    value: "Market & Customer Research"
  },
  { label: "Marketing Strategy", value: "Marketing Strategy" },
  {
    label: "Other - Sales & Marketing",
    value: "Other - Sales & Marketing"
  }
];
export const AnalyticsOption = [
  {
    label: "All Data Science & Analytics",
    value: "All Data Science & Analytics"
  },
  { label: "A/B Testing", value: "A/B Testing" },
  { label: "Data Visualization", value: "Data Visualization" },
  {
    label: "Data Extraction / ETL",
    value: "Data Extraction / ETL"
  },
  {
    label: "Data Mining & Management",
    value: "Data Mining & Management"
  },
  { label: "Machine Learning", value: "Machine Learning" },
  {
    label: "Quantitative Analysis",
    value: "Quantitative Analysis"
  },
  {
    label: "Other - Data Science & Analytics",
    value: "Other - Data Science & Analytics"
  }
];
export const EngineeringOption = [
  {
    label: "All Engineering & Architecture",
    value: "All Engineering & Architecture"
  },
  { label: "3D Modeling & CAD", value: "3D Modeling & CAD" },
  { label: "Architecture", value: "Architecture" },
  { label: "Chemical Engineering", value: "Chemical Engineering" },
  {
    label: "Civil & Structural Engineering",
    value: "Civil & Structural Engineering"
  },
  {
    label: "Contract Manufacturing",
    value: "Contract Manufacturing"
  },
  {
    label: "Electrical Engineering",
    value: "Electrical Engineering"
  },
  { label: "Interior Design", value: "Interior Design" },
  {
    label: "Mechanical Engineering",
    value: "Mechanical Engineering"
  },
  {
    label: "Other - Engineering & Architecture",
    value: "Other - Engineering & Architecture"
  }
];
export const LegalOption = [
  { label: "All Legal", value: "All Legal" },
  { label: "Contract Law", value: "Contract Law" },
  { label: "Corporate Law", value: "Corporate Law" },
  { label: "Criminal Law", value: "Criminal Law" },
  { label: "Family Law", value: "Family Law" },
  {
    label: "Intellectual Property Law",
    value: "Intellectual Property Law"
  },
  { label: "Paralegal Services", value: "Paralegal Services" },
  { label: "Other - Legal", value: "Other - Legal" }
];
export const TranslationOption = [
  { label: "All Translation", value: "All Translation" },
  { label: "General Translation", value: "General Translation" },
  { label: "Legal Translation", value: "Legal Translation" },
  { label: "Medical Translation", value: "Medical Translation" },
  {
    label: "Technical Translation",
    value: "Technical Translation"
  }
];
export const certeficateOption = [
  "English",
  "Frensh",
  "Arabic",
  "Design",
  "Animation",
  "Audio Production",
  "Graphic Design",
  "Illustration",
  "Logo Design & Branding",
  "Photography",
  "Photoshop",
  "3D Modeling & CAD",
  "unity",
  "Java",
  "Javascript",
  "Html5",
  "CSS",
  "ReactJS",
  "React native",
  "Angular",
  "Vue",
  "Architecture",
  "Typography",
  "Interior Design",
  "Mechanical Engineering"
];

export const countries = [
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia And Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, Democratic Republic",
  "Cook Islands",
  "Costa Rica",
  "Cote D'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island & Mcdonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran, Islamic Republic Of",
  "Iraq",
  "Ireland",
  "Isle Of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia, Federated States Of",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barthelemy",
  "Saint Helena",
  "Saint Kitts And Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre And Miquelon",
  "Saint Vincent And Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome And Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia And Sandwich Isl.",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard And Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks And Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis And Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];
